apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    app: frontend
spec:
  containers:
    - name: frontend-container
      image: frontend-image:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 3000
      env:
        - name: REACT_APP_API_URL
          value: "http://backend-srv:8080"